nvim-flutter/flutter-tools.nvim

README.md
While trying to setup the plugin, I got the below error when `neovim` started:
`E5107: Error loading lua [string ":lua"]:15: '}' expected (to close '{' at line 4) near 'lsp'` 
the error was fixed when I added the missing comma in Lua configuration.
PS: sorry to open it as a PR. Please feel free to suggest opening an issue instead. Whichever is best for you.
=> fix(): missing comma in Lua config

README.md, lua/flutter-tools.lua, lua/flutter-tools/config.lua, lua/flutter-tools/executable.lua, lua/flutter-tools/lsp.lua, lua/flutter-tools/utils/init.lua
This PR is based on prior art like [`Dart-Code`](https://github.com/Dart-Code/Dart-Code/blob/81b7711c970e3adb5b2933a3e34e49a39b8e7b07/src/extension/sdk/utils.ts) and [`coc-flutter`](https://github.com/iamcco/coc-flutter/pull/91/files). It's miles off those examples level of complexity for now because it won't support things like `asdf` and `fvm` out of the box. Those will come much later. This should be most useful for people using a `snap` build of flutter, but hopefully doesn't break for mac or other linux users.
It relies on `flutter sdk-path` which I'm not sure yet is universal for all versions of flutter.
Currently hidden behind an experimental flag
```lua
require('flutter-tools').setup {
experimental = { derive_lsp_paths = true }
}
```
=> Automagically try and derive Flutter binary and lsp server paths

README.md, lua/flutter-tools.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/dev_tools.lua, lua/flutter-tools/executable.lua, lua/flutter-tools/lsp.lua, lua/flutter-tools/utils/init.lua, lua/flutter-tools/utils/path.lua
lspconfig is a thin wrapper around starting an lsp server which in actuality isn't that tough to do without it. So this PR removes the dependency since it is not absolutely necessary. Whilst very likely users will have it installed it isn't guaranteed. Also this seems like it gives me more direct control over the lsp server so functionality or configurations won't change underfoot.
EDIT: also tbh I wanted to get more familiar with the native lsp functionality rather than work with/around an abstraction layer
=> Remove dependency on lspconfig

lua/flutter-tools/executable.lua
This PR removes checks for flutter to be executable via the user's `PATH` despite them having passed in an absolute path, it instead attempts to derive the flutter sdk path from the binary path
should fix #30
=> fix: derive flutter sdk path from flutter_path

lua/flutter-tools/guides.lua
Sometimes for reasons I don't understand properly yet the lsp guide ranges are not valid and so no matching character can be found to use for drawing the widgets on a line so for now we omit these
=> fix: ignore invalid end indices

README.md, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/dev_tools.lua, lua/flutter-tools/menu.lua
This PR adds a command to copy the profiler url to the clipboard.
In order to execute the command the app and our own DevTools server must be running (FlutterRun + FlutterCopyProfilerUrl commands)
I've found the following issues while working on this
- As mentioned here, #9 there are some issues with how the DevTools are managed: We don't stop the process. Would be great to have a way to reuse an existing dart devtools process if it's already running and gather its info.
- Chrome and Android have different console outputs regarding the profiler url as mentioned in the [`search_profiler_url`](https://github.com/akinsho/flutter-tools.nvim/compare/main...Charly6596:copy-devtools-link?expand=1#diff-96c4b32009844045b7f1ce3515556a45d330b4b0c2567fa9fed85d0efb0a782fR27) comments. The Android …
=> Add command to copy profiler url

lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/dev_tools.lua
Added an autocmd triggered when vim is closed to kill the devtools process if it was started by the user.
As mentioned in #41, the flutter run command starts a dev tools server if running on mobile and has a parameter to start an already running dev tools server url, so I check if we are running it and pass the url if so.
The autocmd could be used to cleanup other modules if needed.
There is an issue, if we are not running devtools and we start the app, if we wanted to copy the url we would need to start another devtools process with the command, we would have 2 processes, one manage by flutter and another by our plugin
I think we have 3 options
1. Keep it as it is.
2. Always run the dev tools server before running `flutter run` and pass the url as parameter
3. Let flutter start the …
=> fix devtools processes

lua/flutter-tools/commands.lua, lua/flutter-tools/dev_tools.lua, lua/flutter-tools/menu.lua
~~~This depends on #44. The way I detect whether the devtools server is running will be changed once that's merged~~
There are 2 main conditions to group commands: **devtools server running** and **flutter run running**
- `FlutterDevices`
- `FlutterEmulators`
- `FlutterOpenOutline`
- `FlutterLogClear`
- `FlutterCopyProfileUrl`
- `FlutterDevTools`
- `FlutterReload`
- `FlutterRestart`
- `FlutterVisualDebug`
- `FlutterQuit`
- `FlutterRun`
=> Hide disabled commands in telescope menu

README.md, lua/flutter-tools/config.lua, lua/flutter-tools/dev_tools.lua
closes #48 
also fixed a bug in which the value of `profiler_url` is overriden if devtools is not started
A new configuration has been added. This feature is disabled by default
```
dev_tools = {
autostart = false
}
```
=> autostart devtools if not detected

README.md, ftplugin/flutter_tools_notification.vim, lua/flutter-tools/ui.lua
This PR allows a user to override highlights to specifically change the colour of flutter tool notifications. Currently, this is only possible by changing global highlight groups
The groups are 
* `FlutterNotificationNormal` - content of the notification
* `FlutterNotificationBorder` - border of the notification
=> feat: create overridable notification highlights

lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/devices.lua, lua/flutter-tools/utils/init.lua
Add the ability to allow passing commands to flutter run. This is done by taking args via the command line command e.g.
`FlutterRun --flavor dev`
`FlutterRun --no-sound-null-safety`
This means this can also be mapped for reuse e.g.
`nnoremap ,frd <Cmd>FlutterRun --flavor dev`
fixes #70
=> feat: add commandline args for run command

lua/flutter-tools/commands.lua
This PR fixes bug: `attempt to index local 'opts' (a nil value)` when executing Run command in Telescope,
=> fix(telescope): guard against nil opts in Run command from telescope

lua/flutter-tools/guides.lua, lua/flutter-tools/labels.lua, lua/flutter-tools/lsp/code_actions.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/outline.lua, lua/flutter-tools/utils/init.lua
This updates lsp handlers to use the new function signatures and handles
older versions of neovim which do not yet have this.
Relates to https://github.com/neovim/neovim/pull/15504
=> refactor: add compat helper for lsp handlers

lua/flutter-tools/commands.lua, lua/flutter-tools/lsp/init.lua
Hello, 
Currently `flutter run` and `flutter pub get/upgrade` commands are run in neovim `cwd` directory by default.
In my project, the flutter project in a subdir in the monorepo, which means these command fail.
I couldn´t think of any reason not to use the dartls server root_dir config (which is correctly computed by the plugin) as the `cwd` for these commands.
I'm fairly new to neovim so that may be an oversight on my part, please let me know.
Thank you.
=> feat: Execute flutter commands in lsp project root

lua/flutter-tools/lsp/commands.lua
This PR changes `vim.fn.input` to `vim.ui.input` to allow custom ui for the prompt.
=> refactor: use vim.ui.input to prompt for name

lua/flutter-tools/runners/job_runner.lua
This pull request fix the name of callback for plenary job. The incorrect name is causing errors like this issue: [#112](https://github.com/akinsho/flutter-tools.nvim/issues/112)
=> fix: callback name for plenary job execution

lua/flutter-tools/commands.lua, lua/flutter-tools/devices.lua, lua/flutter-tools/runners/dap_runner.lua, lua/flutter-tools/runners/job_runner.lua
#118 
Fix flutter run not using arguments.
This wont work for emulators, I think I can get it to work by just extending the args again and then using the run method instead of emulator run, but im not sure if that might break something else.
=> fix: allow flutter run to take cli arguments

README.md, lua/flutter-tools.lua, lua/flutter-tools/config.lua, lua/flutter-tools/lsp/color/init.lua, lua/flutter-tools/lsp/color/utils.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/utils/init.lua
This PR adds the ability to use the colour information resolved via the LSP to show highlights for a given colour. Unlike colour plugins such as `vim-hexokinase` or `nvim-colorizer` this actually uses the correct material colours and reads colours specified in dart code. 
e.g. It correctly follows the definition of a theme variable
*All* the credit for this work goes to @RRethy, who worked on a PR for nvim but wasn't able to finish it
https://github.com/neovim/neovim/pull/13654
This PR essentially copy pasted his logic into this code base and plugged it in.
cc @sollymay (this is literally a basic copy and paste with very minimal testing, so could be broken)
=> feat: add handler for textDocument/documentColor

lua/flutter-tools/lsp/color/utils.lua
This should fix error:
```
Error executing vim.schedule lua callback: ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:174: attempt to c
all field 'notify' (a nil value)                                                                                        
stack traceback:                                                                                                        
...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:174: in function 'handler'                          
...r/neovim/HEAD-9e1ee9f/share/nvim/runtime/lua/vim/lsp.lua:1097: in function ''                                
vim/_editor.lua: in function <vim/_editor.lua:0>  
```
=> fix: call notify function from correct place

README.md
Regarding the topic discussed in https://github.com/akinsho/flutter-tools.nvim/issues/57 this fix will add another default path to prevent the LSP to load when navigating package code.
Feel free to let me know if there is another way to do the change!
=> chore(readme): mention of excluding pub packages on windows

lua/flutter-tools/lsp/color/init.lua
This fixes the error:
```
E5108: Error executing lua ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:81: Vim(lua):E5108: Error executing lua ...r/neovim/HEAD-35e89bf/share/nvim/runtim
e/lua/vim/lsp.lua:1166: not found: "textDocument/documentColor" request handler for client "jsonls".                                                                     
stack traceback:                                                                                                                                                         
[C]: in function 'error'                                                                                                                                         
...r/neovim/HEAD-35e89bf/share/nvim/runtime/lua/vim/lsp.lua:1166: in function 'request' …
```
=> fix: select only dart language server when requesting color info

ftplugin/dart/lsp.lua, lua/flutter-tools.lua, lua/flutter-tools/lsp/init.lua
Nvim 0.8 introduced `vim.lsp.start` which removes a lot of the hard work of manually starting a server. This PR lays the groundwork for using it, but only for those on nvim nightly for now
=> refactor(lsp): use vim.lsp.start if on nightly

ftplugin/dart/lsp.lua
With the new LSP attach functionality on 0.8 I stated getting `dartls` attached to the buffer several times. Looks like the problem is that `ftplugin` is called several times.
=> fix: attach LSP to buffer only once

lua/flutter-tools.lua
Without this, I need to open any dart file before :FlutterPubGet and :FlutterRun when first entering neovim with pubspec.yaml.
=> feat(setup): add pubspec.yaml as another start point

ftplugin/dart/init.lua, ftplugin/dart/lsp.lua
Copied same configuration as is done there: https://github.com/dart-lang/dart-vim-plugin/blob/master/ftplugin/dart.vim#L16-L18
I also renamed the file from `lsp.lua` to `init.lua`, because now it contains code unrelated to LSP.
Closes #171
=> feat: set dart comments options

lua/flutter-tools/ui.lua
Hello.
If user haven't installed nvim-dap, it fails with the newline error messages.
In short, with this PR:
Without:
=> fix(ui): replace newlines

lua/flutter-tools/lsp/init.lua
I am using [diffview](https://github.com/sindrets/diffview.nvim) plugin, but when trying to open file history I am getting 4 error messages (see screenshot below). LSP server tries to attach to history files but fails because the path starts with `diffview://`. 
The simplest solution is to ignore these buffers. That is what I did in this PR. But not sure if this is the best solution - there could be other plugins that use other file prefixes, so in that case, we need to update the plugin again. One idea was not to attach LSP if the buffer is not modifiable, but that option is added later than attach event.
(We should also fix the problem, that there are 4 error messages instead of 2 and some of them are without any message)
=> fix: do not attach LSP to buffer with diffview file URI

lua/flutter-tools/runners/debugger_runner.lua
Currently, when running via dap, the plugin is not able to detect the profiler_url.
While running with dap debugger, the plugin currently tries to set the profiler_url by trying to read `observatoryUri` from the body of 'event_dart.debuggerUris'.
But, the field `observatoryUri` is not available. The body instead has the field `vmServiceUri` with the websocket uri for the vm service. With this change, the plugin is now able to detect the profiler url and users can run the `FlutterCopyProfilerUrl` command to copy the devtools url
=> fix(dap): read vmServiceUri for profiler_url

lua/flutter-tools/dev_tools.lua, lua/flutter-tools/executable.lua
`flutter pub run devtools` is deprecated. Closes #213
=> fix(devtools): use new dart devtools command

lua/flutter-tools/dap.lua
This fixes the problem with FVM - previously global flutter version was always used. After this change version is picked respecting FVM configuration.
=> fix(dap): use full path to flutter executable when running via DAP

.nvim.json, README.md, ftplugin/flutter_tools_notification.vim, ftplugin/flutter_tools_popup.vim, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/devices.lua, lua/flutter-tools/executable.lua, lua/flutter-tools/lsp/code_actions.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/outline.lua, lua/flutter-tools/ui.lua, lua/flutter-tools/utils/init.lua
When this plugin was first created almost none of the cool new APIs for making plugins existed. So I hand rolled a bunch of things like the menus, the tree layout etc. This stuff now accounts for like 40% of all the code in this repository if not more and there are now well implemented and tested libraries like nui.nvim which provide components for inputs, menus, trees, splits and other complex layouts. 
To simplify maintenance this PR removes all the custom logic for in favour of using nui.nvim for as much/all the custom UI.
=> refactor(ui)!: replace (some) custom ui with `vim.ui.*`

README.md, lua/flutter-tools.lua, lua/flutter-tools/lsp/color/init.lua, lua/flutter-tools/lsp/commands.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/lsp/rename.lua, lua/flutter-tools/lsp/utils.lua, lua/flutter-tools/ui.lua
This command adds support for `updateImportsOnRename` setting (https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration). 
It is useful when the file is renamed after a class rename (when enabled `renameFilesWithClasses` setting). 
It will fall back to `vim.lsp.buf.rename()` if no `dartls` client is found. 
If the client is found, the file is the same as the class name, and the class is being renamed,  it will request for changes via `workspace/willRenameFiles`. Results of `workspace/willRenameFiles` will be applied after the class rename.
To test it try to rename the class that is in the file with the same file name. 
- with `vim.lsp.buf.rename()`: class renamed, file renamed, usage of class renamed, but imports are not …
=> feat: add FlutterRename command

README.md, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/job_runner.lua, lua/flutter-tools/utils/init.lua, tests/commands_spec.lua
Implements #79 
cc @sidlatau here's the branch I mentioned.
Currently the workflow is, a user creates an `exrc` file ie. a `.nvim.lua` or a `.nvimrc` and they add something like
```lua
require('flutter-tools').setup_project({
device = "iPhone10",
flavour = "Production",
})
-- Or
require('flutter-tools').setup_project({
{
device = "iPhone10",
flavour = "Production",
dart_define = {
API_URL = "blah/thing.com",
}
},
{
device = "macOS",
flavour = "Desktop",
}
})
```
I've only implemented support for the device key atm but the others could be added eventually. The plan won't be to support everything immediately, but just to get a system in place for this PR.
=> feat(config): add project configuration

README.md, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua
Whilst the dev log is being populated it receives output from stdout/stderr, if from stderr this is passed on the `vim.notify` this can be very noisy though so this adds an option to silence these notifications
fixes #197
=> feat(commands): add option to silence flutter errors

lua/flutter-tools/lsp/init.lua
use dart language-server --protocol=lsp to start lsp
it should not find snapshot manually
=> chore: use `dart language-server --protocol=lsp`

README.md, doc/flutter-tools.txt, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, tests/commands_spec.lua
- add "target" argument to exrc config
- add "dart-define-from-file" argument to exrc config
=> [feat] exrc config extra arguments

README.md, doc/flutter-tools.txt
Change documentation to show the lazy.nvim install that includes the flutter-tools setup. Eliminates questions like issue #224.
=> Add lazy.nvim install with integrated setup()

lua/flutter-tools/dap.lua
This should fix #207 
Couple questions: how can I test this? Should I use another pattern to detect if we're inside a flutter project?
Also, I'm getting an error when running the configuration (`DAP Error retrieving stack traces: getStack: (112) Service has disappeared`), but it seems to be caused by nvim-dap.
=> fix(dap): define adapter and config when running standalone dart

lua/flutter-tools/dap.lua
This simple PR aims to extend the available commands of `nvim-dap` by adding the custom requests `hotReload` and `hotRestart`. 
Being `customRequests` provided by the `flutter debug_adapter` and not part of the DAP standard payload, it makes sense that the flutter plugin extends these functionalities. 
This can also provide a means to use the hot reload functionality even in debug mode, where, as it is now, it is the only reliable way to run nested complex projects (with project configuration). 
- Extends the `DAP`commands repertoire with `hotReload` and `hotRestart` as `.hot-reload` and `.hot-restart`
=> feat(dap): add custom commands to nvim-dap

lua/flutter-tools/dap.lua
As mentioned in https://github.com/akinsho/flutter-tools.nvim/issues/282 the we need a better way to detect which configs to use - Dart or Flutter.   This PR intents to do that by matching the consequent lines in `pubspec.yaml`
* Dart shelf example: `has flutter = false`
* Flutter counter example: `has flutter = true`
* Commented out 2 lines: `has flutter = false`
* Changed spacing (still valid yaml): `has flutter = true`
* Used tab instead of space: `has flutter = true`
* Removed lines: `has flutter = false`
=> add flutter dependency detection

lua/flutter-tools/lsp/init.lua
For some reason, on one of my projects, LSP tries to attach to a buffer with an empty path. Dart language server recognizes this as `/` root directory and starts to analyze the whole file system and eventually just freezes.
https://github.com/akinsho/flutter-tools.nvim/blob/271eec9edb0f1a2bf30ad449ec3b4eeb2c88af05/lua/flutter-tools/lsp/init.lua#L198
After adding some print statements for debugging, I found out it happens every time the floating window with diagnostic is open. However, there is no such buffer when I check the buffer list with `:ls`, so I'm not sure what exactly causes this. Anyway, check for an empty string is a nice addition to `is_valid_path` function.
=> fix: don't attach lsp to buffer with empty path

lua/flutter-tools/guides.lua
fix #325
I added a default option to set_hl to prevent overwriting custom colors in FlutterWidgetGuids.
=> Fix FlutterWidgetGuides highlight group overwriting custom colors

lua/flutter-tools/dev_tools.lua
This tiny change makes so we don't have to press a key to dismiss the devtools url notification that shows up when the app launches.
Before:
After:
=> fix: remove newline from devtools url notification

lua/flutter-tools/config.lua, lua/flutter-tools/utils/init.lua
This fixes warning in Neovim nightly build. Related to:
https://github.com/neovim/neovim/issues/24572
=> fix: handle deprecated vim.tbl_islist function

lua/flutter-tools/labels.lua
Related issue: https://github.com/akinsho/flutter-tools.nvim/issues/357
Fix: Since the LSP lines can lag behind the document state, we only render labels that are in the buffer lines.
=> fix(ui): render labels only in the document range

README.md, lua/flutter-tools/config.lua, lua/flutter-tools/log.lua
I encountered spammy logs in flutter, that looked something like this:
```
[…]
I/gralloc4( 4115): @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
E/GPUAUX  ( 4115): [AUX]GuiExtAuxCheckAuxPath:666: Null anb
I/gralloc4( 4115): @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
E/GPUAUX  ( 4115): [AUX]GuiExtAuxCheckAuxPath:666: Null anb
I/gralloc4( 4115): @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
E/GPUAUX  ( 4115): [AUX]GuiExtAuxCheckAuxPath:666: Null anb
I/gralloc4( 4115): @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
E/GPUAUX  ( 4115): [AUX]GuiExtAuxCheckAuxPath:666: Null anb
I/gralloc4( 4115): @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
E/GPUAUX  ( 4115): [AUX]GuiExtAuxCheckAuxPath:666: …
```
=> feat: log_filter for flutter output

README.md, doc/flutter-tools.txt, lua/flutter-tools/config.lua, lua/flutter-tools/labels.lua
This PR adds an option to set the priority for the closing tags virtual text.
This would help keep the order of virtual text items configurable, in cases when there are multiple virtual text items, eg.: git blame text from the `gitsigns` plugin or with LSP diagnostics text.
Example:
Current behavior (not preferable, especially in cases when commit messages are longer):
When the priority is set (to 0, in this case) (preferable, as the tag is always kept next to the actual code):
I've kept the default priority to be `0`, as I think logically one would want this text to be closest to the code. Open to discuss if there are any other thoughts on this.
Do let me know your thoughts on this. If this looks like a good change to have, I can add this in the docs (vimdoc and README) as well.
Thanks!
=> feat: Add option to set closing tag virtual text priority

lua/flutter-tools/utils/init.lua
Possibly fixes #378 . Looks like `vim.iter(...):flatten():totable()` is NOT a exact drop-in replacement of `vim.tbl_flatten`. It does not handle nil values. Fixes were made in https://github.com/neovim/neovim/pull/28781 to address the issue.
=> fix: adapt to nvim depractions

README.md, doc/flutter-tools.txt, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/runners/debugger_runner.lua
As `dap` is the default protocol for Flutter, this option is not needed anymore. To toggle debugging, the `config.debugger.enabled` option should be used.
=> refact(debugging): remove `run_via_dap` config option

README.md, lua/flutter-tools/config.lua, lua/flutter-tools/runners/debugger_runner.lua
Without option:
With option:
This option will be enabled by default (DartCode has it enabled too.)
Reference https://github.com/dart-lang/sdk/blob/a70adce28e53ff8bb3445fe96f3f1be951d8a417/pkg/dds/lib/src/dap/adapters/dart.dart#L203
=> feat(dap): add option `evaluate_to_string_in_debug_views`

lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/job_runner.lua
=> feat: respect cwd when detecting is it flutter project, handle running dart-only projects

lua/flutter-tools/commands.lua, lua/flutter-tools/utils/yaml_parser.lua
I am using the same code as in https://github.com/nvim-flutter/pubspec-assist.nvim/blob/main/lua/pubspec-assist/parser.lua to parse yaml.
It should be a more reliable way to check if flutter dependency exists in the `pubspec.yaml`.
=> fix: use yaml parser for flutter dependency detection in pubspec.yaml

lua/flutter-tools.lua
Previously `FlutterRun` and other plugin commands were created only if .dart or pubspec.yaml file were opened. This change will register plugin commands on project config setup. So flutter app will be possible to start without need to open dart file first.
=> feat: setup plugin on `require("flutter-tools").setup_project`

README.md, doc/flutter-tools.txt, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/log.lua
- Added a new command `FlutterLogToggle` to toggle the visibility of the log buffer.
- Updated the documentation to include the new command. 
- Modified the log function to use the same buffer number when appending lines.
- Adjusted the open command for the log buffer to use a horizontal split.
=> feat(log): add toggle command for log buffer

lua/flutter-tools/commands.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/job_runner.lua, lua/flutter-tools/runners/vm_service_extensions.lua
- Rename widget_inspector to inspect_widget for consistency
- Rename construction_lines to paint_baselines to match Flutter API
- Add error handling when calling VM service extensions
- Fix toggle value logic for VM service extensions
=> fix(commands): make inspect widget command work in debug runner

ftplugin/dart/init.lua
This PR adds the buffer scoped variable `flutter_tools_did_ftplugin`.
With this variable the user can manually disable the filetype plugin code bundled with `flutter-tools.nvim`. This can be useful in case someone wants different configuration options for dart only projects (like CLI tools, etc.) which are not dependent on the Flutter SDK. 
See my [init.lua](https://gitlab.com/obemu/init.lua/-/blob/master/after/plugin/20_setup_flutter_dart.lua?ref_type=heads) for an example on how that could be used.
=> Added option to disable ftplugin

lua/flutter-tools/runners/debugger_runner.lua
DAP automatically detects async runtime and tries to yield across C-call. Adding empty callback fixes it.
```
Error detected while processing BufWritePost Autocommands for "*.dart":
Error executing lua callback: ...tools.nvim/lua/flutter-tools/runners/debugger_runner.lua:285: attempt to yield across C-call boundary
stack traceback:
[C]: in function 'request'
...tools.nvim/lua/flutter-tools/runners/debugger_runner.lua:285: in function 'send'
...m/lazy/flutter-tools.nvim/lua/flutter-tools/commands.lua:337: in function 'send'
...m/lazy/flutter-tools.nvim/lua/flutter-tools/commands.lua:345: in function 'reload'
...share/nvim/lazy/flutter-tools.nvim/lua/flutter-tools.lua:102: in function <...share/nvim/lazy/flutter-tools.nvim/lua/flutter-tools.lua:102>
```
=> fix: fix dap crash on BufWritePost

lua/flutter-tools/dev_tools.lua
Addresses #434 . 
The job runner was returning nil values so added a check at the start of handle log to make sure data is not nil.
=> fix: check for nil value when handle_log is called

lua/flutter-tools/lsp/init.lua
Related to https://github.com/neovim/neovim/issues/32384 
vim.lsp.buf.definition() no longer uses the handler so we can not reuse it in "dart/textDocument/super" handling.
=> fix(lsp): restore dart go to super functionality

lua/flutter-tools/commands.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/job_runner.lua
This fixes `FlutterDebug` command when multiple devices are available. Previously `force_debug` option was not passed to `on_run_exit` callback
=> fix(flutter-debug): pass run options to runner callbacks

lua/flutter-tools/executable.lua
Now using 'vim.fn.exepath' to retrieve the correct value for the flutter executable, when using fvm on windows. Previously the plugin set the flutter executable to the UNIX script ("flutter") but Windows has its' own version ("flutter.bat").
=> Bugfix in module executable.lua on Windows

README.md, lua/flutter-tools.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/runners/debugger_runner.lua
- Made debugging integration more resilient when nvim-dap isn't installed
- Improved documentation for debugger configuration
- Restructured how debugger configurations are registered
- Simplified setup process by making DAP configuration automatic
=> fix(dap): improve debugger integration with nvim-dap

lua/flutter-tools/config.lua, lua/flutter-tools/lsp/color/utils.lua, lua/flutter-tools/utils/path.lua
This fixes https://github.com/nvim-flutter/flutter-tools.nvim/issues/457
=> fixed deprecated syntax for vim.validate

lua/flutter-tools/executable.lua
The plugin does not work with FVM on Windows. I tested this on two separate projects using Flutter versions 3.16.0 and 3.27.0.
When running the `FlutterRun` command, the following error occurs:
```swift
Error executing Lua callback:
...plenary/job.lua:406: Failed to spawn process:
command = "C:\\Users\\vasil\\fvm\\versions\\3.27.0\\bin\\flutter"
pid = "ENOENT: no such file or directory"
```
This happens because the plugin tries to run flutter directly, but on Windows the actual executable is `flutter.bat`.
If `path.is_windows == true`, we now append `.bat` to the path of the flutter binary. This fixes the issue and allows flutter-tools.nvim to work correctly with FVM on Windows.
I've been using this fix for several weeks without issues.
OS: Windows 11 Home
fvm: v3.2.1
flutter-tools.nvim: …
=> fix(fvm/windows): append '.bat' extention to flutter path

lua/flutter-tools/commands.lua
Fixes fvm list and fvm use on windows
=> fix(fvm/windows): append .bat extension on fvm command

lua/flutter-tools/ui.lua
https://github.com/nvim-flutter/flutter-tools.nvim/issues/366.
This workaround exclude log buffer included in session.
=> fix: Buffer is not 'modifiable'

lua/flutter-tools/commands.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/lsp/utils.lua, lua/flutter-tools/utils/config_utils.lua, lua/flutter-tools/utils/init.lua, lua/flutter-tools/utils/path.lua
This fixes the use of commands in monorepos as we always go up the directory tree searching for the nearest project root marker,
instead of relying on the LSP's root dir which is set to be the project root of whichever project was open when the LSP got attached.
=> feat: improves project root detection by always going up the directory tree until we find a project root marker
