README.md, lua/flutter-tools.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/executable.lua, lua/flutter-tools/lsp.lua
So far the debug module provides 2 bits of functionality
* This should install the debugger
* Setup some dart config for dap
=> Basic integration with nvim-dap to provide debug capabilites

lua/flutter-tools/executable.lua
=> Fix lsp_derive_paths: wrong argument passed to vim.list_slice

README.md, lua/flutter-tools/lsp.lua, lua/flutter-tools/utils/path.lua
@RobertBrunhage can you try this PR and see if it still fixes the lag mention in #57. This adds the exclusion by default, and notes that in the README if a user wanted this behaviour for some reason.
fixes #57
=> fix: don't analyse flutter sdk packages

README.md
The changes noted in this section made it to 0.5 stable
=> Removed deprecated notice in README.md

lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/menu.lua
closes #42 
With and without arguments :+1: 
The output will be in a floating window for 10 seconds.
=> Add command for pub upgrade

README.md, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/decorations.lua, lua/flutter-tools/utils/init.lua
The long term goal will be to provide bits of information that a user can
add to their nvim. For now, it's focused primarily on information that can be added to a user's statusline (not really sure what else applies other than the statusline).
The first item will be the app version since I use/need this often so was the initial inspiration.
I might also try and add the name of the running device as another item.
=> feat: add (statusline) decorations

lua/flutter-tools/labels.lua
Also make sure the hl_mode is combine so it doesnt stand over the cursorline
=> feat(labels): Update to use extmarks

README.md, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/dev_tools.lua, lua/flutter-tools/log.lua, lua/flutter-tools/runners/dap_runner.lua, lua/flutter-tools/runners/job_runner.lua
Fixes https://github.com/akinsho/flutter-tools.nvim/issues/91
=> feat: Introduce dap-based runner

README.md, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/runners/dap_runner.lua, lua/flutter-tools/runners/job_runner.lua
=> feature: add flutter detach command

lua/flutter-tools/guides.lua
=> fix(guides): show guides for first child and adjust start index

lua/flutter-tools/commands.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/runners/dap_runner.lua, lua/flutter-tools/runners/job_runner.lua
This adds a widget inspector and a construction lines toggle to the "Command Palette".
=> feat(commands): add widget inspector and construction lines

lua/flutter-tools/guides.lua
=> fix(guides): do not draw guides over text

lua/flutter-tools/lsp/color/init.lua
=> fix: check colorProvider capability before sending a request

lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/lsp/color/init.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/runners/job_runner.lua
Hi, I think opening dev tools directly is more convenient than copying profile url and opening browser manually.
=> feat(commands): open dev tools

README.md, lua/flutter-tools.lua, lua/flutter-tools/lsp/init.lua
FlutterSuper respects Spec: https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md#darttextdocumentsuper-method
FlutterReanalyze respects Spec: https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#dartreanalyze-method.
=> feat(commands): add FlutterSuper and FlutterReanalyze

README.md
=> docs: add `background_color` to lsp.color config documentation

lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/dev_tools.lua, lua/flutter-tools/devices.lua, lua/flutter-tools/executable.lua, lua/flutter-tools/guides.lua, lua/flutter-tools/labels.lua, lua/flutter-tools/log.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/outline.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/job_runner.lua, lua/flutter-tools/ui.lua, lua/flutter-tools/utils/init.lua
To closer match the now stabilized builtin.
When this plugin was first developed, `nvim-notify` and `vim.notify` did not exist so this plugin created it's own custom mechanism for it. This is in the long run a pain to continue to maintain and we can just defer to the new mechanisms for this.
@sidlatau @rlch can either (both) of you try this locally and see if there are any errors in your usage as I've changed every spot where notify was used and there could easily be breakage 🙏🏿
=> feat(ui)!: change vim.notify function signature

lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/decorations.lua, lua/flutter-tools/dev_tools.lua, lua/flutter-tools/devices.lua, lua/flutter-tools/executable.lua, lua/flutter-tools/guides.lua, lua/flutter-tools/labels.lua, lua/flutter-tools/lazy.lua, lua/flutter-tools/log.lua, lua/flutter-tools/lsp/code_actions.lua, lua/flutter-tools/lsp/commands.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/outline.lua, lua/flutter-tools/ui.lua
This mechanism delays actually requiring a module till the module is actually accessed
=> refactor(lazy): replace requires with lazy requires

README.md, lua/flutter-tools.lua, lua/flutter-tools/commands.lua, lua/flutter-tools/decorations.lua, lua/flutter-tools/lsp/init.lua, lua/flutter-tools/outline.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/job_runner.lua, lua/flutter-tools/utils/init.lua
Selecting works, but unselecting does not, looks like that `shutdown` function is not called. Also, I see there is `FlutterToolsAppStarted` autocommand, but it does not work for me if I use it. So I created a new one here. 
@akinsho  what is your opinion about adding this info to decorations?
=> feat(decorations): view selected project config in statusline

README.md, doc/flutter-tools.txt, lua/flutter-tools/config.lua, lua/flutter-tools/lsp/init.lua
Can help #180 with root_patterns = { ".git", ".metadata" },
=> feat: add root_patterns to config

lua/flutter-tools/lsp/rename.lua
=> fix: FlutterRename when files with import is opened in another buffer

lua/flutter-tools/runners/debugger_runner.lua
In `launch.json` it is possible to specify the current working directory (cwd). 
This can be used in complex projects to create configurations based on the main package, which in turn does not need the `program` param. 
It is more of a proposal than an actual fix; it heightens the inter-compatibility with how it functions in vs code. 
- Keeps `.cwd` if specified in the project config
- Changes `pick_one_sync` with `.pick_if_many` allowing the use of `vim.ui.select()`
=> fix(dap): fix cwd not being considered

lua/flutter-tools/commands.lua
This PR fix https://github.com/akinsho/flutter-tools.nvim/issues/280
=> fix(commands): set current device while running project

lua/flutter-tools/commands.lua, lua/flutter-tools/menu.lua
This is the updated version of akinsho/flutter-tools.nvim/pull/285, which additionally adds arguments from the project config.
=> feat(commands): add install/uninstall commands to menu

README.md, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, tests/commands_spec.lua
It will add possibility to run app in `profile`, `release` modes.
=> feat: add option to configure flutter mode via config

README.md, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua
=> feat: add web port param to config

lua/flutter-tools/commands.lua, lua/flutter-tools/menu.lua, lua/flutter-tools/runners/debugger_runner.lua, lua/flutter-tools/runners/vm_service_extensions.lua
=> feat: add performance_overlay, repaint_rainbow and slow_animations commands

lua/flutter-tools/executable.lua
As pointed in https://fvm.app/documentation/getting-started/faq#monorepo-support FVM could be set at the root of monorepo.
=> feat(fvm): support FVM in monorepo setup

lua/flutter-tools/lsp/color/utils.lua
Fix: Similar vein to https://github.com/akinsho/flutter-tools.nvim/pull/360
Checking for if the line is within the buffer range.
=> fix(ui): add check for line in buffer range

README.md, doc/flutter-tools.txt, lua/flutter-tools/commands.lua, lua/flutter-tools/config.lua, lua/flutter-tools/dap.lua, lua/flutter-tools/runners/debugger_runner.lua
=> feat(config): add possibility to provide cwd via project configuration

lua/flutter-tools/dev_tools.lua
My PR consists of 3 things:
1.  The `version.lua` module
This module exposes the three functions `version`, `flutter_version` and `dart_version`. It also adds the classes `flutter.FlutterVersion` and `flutter.SemVer`. The functions can be called and used similarly to `get`, or `flutter` in the `executable.lua` module.
Now this module is currently not being used anywhere else because the reason why I thought I needed it was a misunderstanding on my side, nevertheless I thought it could be useful in the future and kept it.
2. Improved types in the `executable.lua` module
The type hint for the callback that must be provided to `get`, `flutter`, and `dart`, which receives the value to the flutter/dart binaries/SDKs was bad, because the function receives a `table<string, string>` and the user …
=> refactor: use plenary job to open devtools in browser

lua/flutter-tools/outline.lua
- Refactor outline URI storage to buffer level variable
- Add outline URI validation in get_outline_content checks
- Pass outline URI consistently through refresh_outline function
=> fix(outline): improve outline URI handling

lua/flutter-tools/config.lua, lua/flutter-tools/lsp/init.lua
- The analysis server can be used to understand LSP performance issues.
=> feat: adds analyzer_web_port config which starts the LSP analysis server with the given port
